apiVersion: v1
kind: Service
metadata:
  name: oraclehrmsintfrontendservice
spec:
  selector:
    app: oraclehrmsintfrontendapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30031
  type: NodePort
