FROM eclipse-temurin

WORKDIR /sp/app

# Install wget
RUN apt-get update && apt-get install -y wget

# Download the file using wget
RUN wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1lY-ANcnWqySVEiTnQunONrsTFdJo5-i0" -O UnifiedHRMS.jar

EXPOSE 8459

CMD ["java", "-jar", "UnifiedHRMS.jar"]
