apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrunifybaseprojectdeployment
spec:
  selector:
    matchLabels:
      app: hrunifybaseprojectapp
  template:
    metadata:
      labels:
        app: hrunifybaseprojectapp
    spec:
      containers:
      - name: hrunifybaseprojectcontainer
        image: hrunifybaseproject:viveksawale
        ports:
        - containerPort: 8459
