apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvccareerhistory
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
