apiVersion: v1
kind: Service
metadata:
  name: careerhistoryservice
spec:
  selector:
    app: careerhistoryhrmoraclepod
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30011
  type: NodePort
